# Common profile (sourced once at login)

export LANG=en_US.UTF-8

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

export PATH="$PATH:$HOME/.local/bin"

# Source local profile overrides (generated by install.sh)
source "$HOME/.zlocalprofileoverride"
