#!/usr/bin/env sh

# # find "$HOME/.config/yabai" - type f -perm +111 -exec {} \;
# # bsp, stack or float
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#
# yabai -m config layout bsp
# yabai -m config auto_balance on
#
# # New window spawns to the right if vertical split, or bottom if horizontal split
#
# yabai -m config window_placement second_child
#
# # padding
#
# yabai -m config top_padding 0
# yabai -m config bottom_padding 0
# yabai -m config left_padding 0
# yabai -m config right_padding 0
# yabai -m config window_gap 1
#
# # mouse
#
# # center mouse on window with focus
#
# yabai -m config mouse_follows_focus on
# yabai -m config focus_follows_mouse autoraise
#
# yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# # modifier for clicking and dragging with mouse
#
# yabai -m config mouse_modifier alt
#
# # set modifier + left-click drag to move window
#
# yabai -m config mouse_action1 move
#
# # set modifier + right-click drag to resize window
#
# yabai -m config mouse_action2 resize
#
# # when window is dropped in center of another window, swap them (on edges it will split it)
#
# # yabai -m mouse_drop_action swap
#
# # disable apps
#
# yabai -m rule --add app="^System Settings$" manage=off
# yabai -m rule --add app="^Calculator$" manage=off
# # yabai -m rule --add app="^Karabiner-Elements$" manage=off
# yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off
# # yabai -m rule --add title="^Picture in Picture$" manage=off mouse_follows_focus=off
#

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config mouse_follows_focus off \
  focus_follows_mouse off \
  window_zoom_persist off \
  window_placement second_child \
  window_shadow float \
  split_ratio 0.50 \
  auto_balance off \
  auto_padding on \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  top_padding 0 \
  bottom_padding 0 \
  left_padding 0 \
  right_padding 0 \
  window_gap 1

# window_opacity on \
# window_opacity_duration 0.2 \
# active_window_opacity 1.0 \
# normal_window_opacity 0.8 \
# insert_feedback_color 0xff9dd274 \
# window_animation_duration 0.5 \
# window_animation_easing ease_out_quint \
# external_bar               all:40:0       \

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m config layout bsp
