#! /usr/bin/env zsh
# find "$HOME/.config/yabai" - type f -perm +111 -exec {} \;
# bsp, stack or float

# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa

yabai -m config layout bsp
yabai -m config auto_balance on

# New window spawns to the right if vertical split, or bottom if horizontal split

yabai -m config window_placement second_child

# padding

yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 2

# mouse

# center mouse on window with focus

yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# modifier for clicking and dragging with mouse

yabai -m config mouse_modifier alt

# set modifier + left-click drag to move window

yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window

yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)

# yabai -m mouse_drop_action swap

# disable apps

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
# yabai -m rule --add app="^(Arc)$" subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off
# yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off
# yabai -m rule --add title="^Picture in Picture$" manage=off mouse_follows_focus=off


# yabai -m rule --add app="^(Arc)$" subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off
