-- return {
--   "zbirenbaum/copilot.lua",
--   enabled = false,
--   opts = {
--     -- suggestion = {
--     --   enabled = not vim.g.ai_cmp,
--     --   auto_trigger = true,
--     --   hide_during_completion = vim.g.ai_cmp,
--     --   keymap = {
--     --     accept = false, -- handled by nvim-cmp / blink.cmp
--     --     next = "<M-]>",
--     --     prev = "<M-[>",
--     --   },
--     -- },
--     -- panel = { enabled = false },
--     filetypes = {
--       markdown = true,
--       help = true,
--       ts = true,
--       lua = true,
--     },
--   },
-- }

return {
  -- {
  --   "supermaven-inc/supermaven-nvim",
  --   config = function()
  --     require("supermaven-nvim").setup({
  --       keymaps = {
  --         accept_suggestion = "<Tab>",
  --         clear_suggestion = "<C-]>",
  --         accept_word = "<C-j>",
  --       },
  --       color = {
  --         suggestion_color = "#ffffff",
  --         cterm = 244,
  --       },
  --       log_level = "info", -- set to "off" to disable logging completely
  --       disable_inline_completion = false, -- disables inline completion for use with cmp
  --       disable_keymaps = false, -- disables built in keymaps for more manual control
  --       condition = function()
  --         return false
  --       end, -- condition to check for stopping supermaven, `true` means to stop supermaven when the condition is true.
  --     })
  --   end,
  -- },
}
